#!/bin/bash
#SBATCH -N 1      # nodes requested
#SBATCH --job-name=roman-empire-bdl
#SBATCH --output=roman-empire-bdl.out
#SBATCH --error=roman-empire-bdl.err
#SBATCH --mem=36000
#SBATCH --qos=normal
#SBATCH --gres=gpu:1
# the -u option means 'unbuffered',
# which should continuously write output to the .out file
srun -u python -m train --name BDL-l5 --dataset roman-empire --model BDLSAGE --num_layers 5 --device cuda:0 --num_bundles 8
